// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsw1iViGJ8Z1CgyWSSCAGGbbYNUccV7Bs',
    appId: '1:758856710004:web:bcd8dca8f4faa206a29e21',
    messagingSenderId: '758856710004',
    projectId: 'liga-nerdola',
    authDomain: 'liga-nerdola.firebaseapp.com',
    storageBucket: 'liga-nerdola.firebasestorage.app',
    measurementId: 'G-DK8RT6KQJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAXCuAgA6GAVXARMG-J34K9qs-_DSvT4',
    appId: '1:758856710004:android:e4d4edaa219a5a6ea29e21',
    messagingSenderId: '758856710004',
    projectId: 'liga-nerdola',
    storageBucket: 'liga-nerdola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oaKz81g8DppxCf8S2ZpPD3tcTsik69g',
    appId: '1:758856710004:ios:1f05844488c1f635a29e21',
    messagingSenderId: '758856710004',
    projectId: 'liga-nerdola',
    storageBucket: 'liga-nerdola.firebasestorage.app',
    iosBundleId: 'com.example.ligaNerdola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6oaKz81g8DppxCf8S2ZpPD3tcTsik69g',
    appId: '1:758856710004:ios:1f05844488c1f635a29e21',
    messagingSenderId: '758856710004',
    projectId: 'liga-nerdola',
    storageBucket: 'liga-nerdola.firebasestorage.app',
    iosBundleId: 'com.example.ligaNerdola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsw1iViGJ8Z1CgyWSSCAGGbbYNUccV7Bs',
    appId: '1:758856710004:web:137ab2ed98113591a29e21',
    messagingSenderId: '758856710004',
    projectId: 'liga-nerdola',
    authDomain: 'liga-nerdola.firebaseapp.com',
    storageBucket: 'liga-nerdola.firebasestorage.app',
    measurementId: 'G-0DPBQP9Q98',
  );
}
